#!/bin/bash

# Script to switch to ADSL modem configuration

# Check if interface name is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <INTERFACE_NAME>"
  exit 1
fi

INTERFACE_NAME="$1"
IP_ADDRESS="192.168.1.100"
NETMASK="255.255.255.0" # or /24
GATEWAY="192.168.1.1"
DNS_SERVER="8.8.8.8"

echo "Attempting to switch to ADSL modem (Gateway: ${GATEWAY}) for interface ${INTERFACE_NAME}..."

# Check if NetworkManager is available
if command -v nmcli &> /dev/null; then
    echo "Using NetworkManager (nmcli) to configure interface..."

    # Get the connection name associated with the interface.
    # This is often the same as the interface name or like "Wired connection 1"
    # We try to find an active connection on the device first.
    CONNECTION_NAME=$(nmcli -g NAME,DEVICE,STATE con show --active | grep "${INTERFACE_NAME}:activated" | awk -F: '{print $1}' | head -n 1)

    if [ -z "$CONNECTION_NAME" ]; then
        # If no active connection, try to find any connection for the device
        CONNECTION_NAME=$(nmcli -g NAME,DEVICE con show | grep "${INTERFACE_NAME}" | awk -F: '{print $1}' | head -n 1)
    fi

    if [ -z "$CONNECTION_NAME" ]; then
        echo "Error: Could not find an existing NetworkManager connection for interface ${INTERFACE_NAME}."
        echo "Please ensure the interface has a connection profile in NetworkManager."
        exit 1
    fi

    echo "Found NetworkManager connection: ${CONNECTION_NAME}"

    # Configure IP address, gateway, and DNS
    nmcli con mod "${CONNECTION_NAME}" ipv4.method manual ipv4.addresses "${IP_ADDRESS}/24" ipv4.gateway "${GATEWAY}" ipv4.dns "${DNS_SERVER}"

    # Bring the connection down and up to apply changes
    # Note: This can interrupt connectivity.
    echo "Applying changes by reactivating connection '${CONNECTION_NAME}'..."
    nmcli con down "${CONNECTION_NAME}" && nmcli con up "${CONNECTION_NAME}"

    if [ $? -eq 0 ]; then
        echo "Successfully switched to ADSL modem configuration for interface ${INTERFACE_NAME} using NetworkManager."
        echo "IP: ${IP_ADDRESS}/24, Gateway: ${GATEWAY}, DNS: ${DNS_SERVER}"
    else
        echo "Error: Failed to apply ADSL modem configuration using NetworkManager."
        # Attempt to revert to DHCP if modification failed badly.
        # nmcli con mod "${CONNECTION_NAME}" ipv4.method auto
        exit 1
    fi
elif command -v ip &> /dev/null; then
    echo "Using 'ip' command to configure interface (NetworkManager not found)..."
    echo "Note: 'ip' command changes may not persist across reboots or NetworkManager taking control."

    # Set IP address and subnet mask
    ip addr flush dev "${INTERFACE_NAME}" # Remove old IP addresses
    ip addr add "${IP_ADDRESS}/24" dev "${INTERFACE_NAME}"

    # Set default gateway
    # Remove existing default gateways before adding a new one
    ip route del default
    ip route add default via "${GATEWAY}" dev "${INTERFACE_NAME}"

    # Setting DNS with `ip` command is not straightforward as it depends on how resolv.conf is managed.
    # Typically, /etc/resolv.conf is managed by NetworkManager, systemd-resolved, or resolvconf.
    # Manually editing /etc/resolv.conf is often overwritten.
    echo "DNS Configuration: Please ensure /etc/resolv.conf is configured correctly."
    echo "You might need to manually edit it or configure your system's DNS resolver."
    echo "For example, add 'nameserver ${DNS_SERVER}' to /etc/resolv.conf."
    # A common way if systemd-resolved is not dominant:
    if [ -f /etc/resolv.conf ] && grep -q "Generated by NetworkManager" /etc/resolv.conf; then
        echo "Warning: /etc/resolv.conf seems to be managed by NetworkManager. Manual DNS changes might be overwritten."
    fi
    # A simple approach, but might be overwritten:
    # echo "nameserver ${DNS_SERVER}" > /etc/resolv.conf

    echo "Successfully switched to ADSL modem configuration for interface ${INTERFACE_NAME} using 'ip' commands."
    echo "IP: ${IP_ADDRESS}/24, Gateway: ${GATEWAY}"
    echo "DNS: Remember to set DNS to ${DNS_SERVER} if not handled by other means."
else
    echo "Error: Neither 'nmcli' nor 'ip' command found. Cannot configure network."
    exit 1
fi

echo "Script finished."
